glider_image: "glider-icon.png"

regions:
  gulfstream:
    label: "Gulf Stream"

  california:
    label: "California"

  gulfofmaine:
    label: "Gulf of Maine"

  gulfofmexico:
    label: "Gulf of Mexico"

  midatlantic:
    label: "Mid-Atlantic"

  hatteras:
    label: "Hatteras"

  indian:
    label: "Indian Ocean"

  bayofbengal:
    label: "Bay of Bengal"

  galapagos:
    label: "Galapagos"

  iceland:
    label: "Iceland"
