glider_image: "glider-icon.png"

regions:
  auto:
    label: "Auto"
    enabled: true
    default: true

  gulfstream:
    label: "Gulf Stream"
    enabled: true
    center:
      lat: 35.0
      lon: -65.0
    zoom: 6

  global:
    label: "Global"
    enabled: true
    center:
      lat: 0
      lon: 0
    zoom: 1.5
