current_members:
  - name: Robert E. Todd
    role: Associate Scientist, Principal Investigator
    image: rtodd26_IMG_5156.jpg
    blurb: Robert is a physical oceanographer at WHOI whose research largely focuses on boundary current systems and upper ocean processes. After undergraduate work at North Carolina State University and graduate work at the Scripps Institution of Oceanography, he came to WHOI in 2011 and has been here ever since. Outside of work, Robert enjoys running, sailing, photography, and traveling with his wife and two kiddos.
    email: rtodd@whoi.edu
    website: https://rtodd.whoi.edu

  - name: Patrick Deane
    role: Engineer II
    image: pdeane_202605_fish.jpg
    blurb:
    email: pdeane@whoi.edu
    website:

  - name: Edie Salzig
    role: Engineering Assistant III
    image: esalzig_IMG_6210.jpeg
    blurb:
    email: eden.salzig@whoi.edu
    website:

  - name: Sidney Batchelder
    role: Information Systems Associate III
    image: sidney.png
    blurb: Website Design and Maintenance
    email: sbatchelder@whoi.edu
    website: 

previous_members:
  - name: Breck Owens
    role: Emeritus Research Scholar
    email:
    website:

  - name: Larry George
    role: Engineer II
    blurb:
    email:
    website:

  - name: Julie Jakoboski
    role: MIT-WHOI Joint Program Student
    now: MetOcean Solutions, New Zealand
    email:
    website:

  - name: Joleen Heiderich
    role: MIT-WHOI Joint Program Student
    email:
    website:

  - name: Kyle R. Kausch
    role: MIT-WHOI Joint Program Student
    now: LCDR, US Navy
    email:
    website:

  - name: Alice S. Ren
    role: Postdoctoral Investigator
    now: Assistant Professor at Bermuda Institute of Ocean Sciences, Arizona State University
    email:
    website:

  - name: Devon Gaynes
    role: Summer Student Fellow
    email:
    website:
